# NumPy essentials

In [2]:
import numpy as np

Firstly I have to create array

I can create array of zeros

In [3]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [4]:
b=np.zeros(20)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

The Shape changes a shape of array

In [5]:
b.shape=(10,1)
b

ValueError: cannot reshape array of size 20 into shape (10,1)

In [6]:
b.shape

(20,)

I can create array of ones or empty array

In [7]:
c=np.ones(3)
c

array([1., 1., 1.])

In [8]:
c=np.empty(5)
c

array([0., 0., 0., 0., 0.])

I can create array of values distributed in the array. This could be used for x-axis.

In [10]:
c=np.linspace(0,10,11) #from 0 to 100 with 11 elements
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Creation of NumPy array from the Phyton list

In [1]:
c=np.array([10,20])
c

NameError: name 'np' is not defined

In [ ]:
a_list=[1,2,3,4,5,6,7,8]
a=np.array(a_list)
a

#### NumPy array from 2-dimmensional Python list

In [ ]:
b_list=[[1,2,3,4],[14,15,16,18]]
b=np.array(b_list)
print(b[1,3])
print(b)

#### Reshaping of the NumPy array 

In [ ]:
b.shape=(1,8)
b

In [ ]:
b.shape=(8,1)
b

### How to generate random NumPy array

In [ ]:
np.random.seed(0)
z=np.random.randint(5,size=10)
z

In [ ]:
np.random.seed(0)
z=np.random.randint(10,size=(4,5))
z

Generate a 1 x 3 array with 3 different upper bounds

In [ ]:
np.random.randint(1, [10, 5, 10])

Generate a 1 by 3 array with 3 different lower bounds

In [ ]:
np.random.randint([1, 5, 7], 10)

### How to access elements of array

It is the same as a Python list

In [ ]:
z[1] #second element of array

In [ ]:
z[0:2] #first two elements of array

In [ ]:
z[-1] #last element of the array

### Statistical operations

In [ ]:
z=np.array([[1,2,3,4],[1,2,1,1]])
z

In [ ]:
print(np.sum(z))
print(np.prod(z))
print(np.mean(z))
print(np.std(z))
print(np.var(z))
print(np.min(z))
print(np.max(z))

### Mathematical operations

In [ ]:
a_array=np.array([1,2,3])
b_array=np.array([4,5,6])

In [ ]:
a_array+b_array #it adds each corresponding element together and creates new array of results

In [ ]:
a_array+30 #to each element add 30

In [ ]:
a_array*b_array #it multiplies each corresponding together and creates new array of results

In [ ]:
a_array*10 #each element is multiplied by 10 

In [ ]:
a_array@b_array #dot product

### Array operations

In [ ]:
z.T  #it transposes array

In [ ]:
np.sort(a_array)

In [ ]:
np.sort(z)